name: Online Store App CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #check out the code from repository
      - name: Checkout code
        uses: actions/checkout@v4

      # set up a .NET environment 
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' #we should change it based on the actual version used!

      #restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # the application build
      - name: Build the application
        run: dotnet build --configuration Release

      #running the unit tests
      - name: Run tests
        run: dotnet test --configuration Release
